_wandb:
    value:
        cli_version: 0.23.1
        e:
            b4b087bhuwv7u2w27la9ud973edrb6ap:
                email: jan.batman4@gmail.com
                executable: /Users/brader/Desktop/stock-dashboard/venv/bin/python
                git:
                    commit: c814c723c1e3b4c8c4c1869bfab79c4aad71bdbd
                    remote: https://github.com/jjedra4/stock-dashboard.git
                host: Jans-MacBook-Air.local
                os: macOS-15.0.1-arm64-arm-64bit-Mach-O
                program: -m src.model.tuning
                python: CPython 3.13.2
                root: /Users/brader/Desktop/stock-dashboard
                startedAt: "2025-12-05T20:58:42.649285Z"
                writerId: b4b087bhuwv7u2w27la9ud973edrb6ap
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "2":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.2
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": darwin-arm64
colsample_bytree:
    value: 0.8750462710648802
learning_rate:
    value: 0.03598965249210712
max_depth:
    value: 2
n_estimators:
    value: 329
reg_alpha:
    value: 9.758793290779666
reg_lambda:
    value: 6.775354642493415
subsample:
    value: 0.9315347923283698
