_wandb:
    value:
        cli_version: 0.23.1
        e:
            fl5te9c3s6un4kiobrnz7045wucmeo2i:
                email: jan.batman4@gmail.com
                executable: /Users/brader/Desktop/stock-dashboard/venv/bin/python
                git:
                    commit: c814c723c1e3b4c8c4c1869bfab79c4aad71bdbd
                    remote: https://github.com/jjedra4/stock-dashboard.git
                host: Jans-MacBook-Air.local
                os: macOS-15.0.1-arm64-arm-64bit-Mach-O
                program: -m src.model.tuning
                python: CPython 3.13.2
                root: /Users/brader/Desktop/stock-dashboard
                startedAt: "2025-12-05T21:03:27.579544Z"
                writerId: fl5te9c3s6un4kiobrnz7045wucmeo2i
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "2":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.2
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": darwin-arm64
colsample_bytree:
    value: 0.6481248085153661
learning_rate:
    value: 0.008571685065777077
max_depth:
    value: 14
n_estimators:
    value: 382
reg_alpha:
    value: 5.010090287260193
reg_lambda:
    value: 9.854478184952344
subsample:
    value: 0.7891778582666372
