_wandb:
    value:
        cli_version: 0.23.1
        e:
            r2bu9rmhcy6kzyrtd7k9dzbpbkmrqu3x:
                email: jan.batman4@gmail.com
                executable: /Users/brader/Desktop/stock-dashboard/venv/bin/python
                git:
                    commit: c814c723c1e3b4c8c4c1869bfab79c4aad71bdbd
                    remote: https://github.com/jjedra4/stock-dashboard.git
                host: Jans-MacBook-Air.local
                os: macOS-15.0.1-arm64-arm-64bit-Mach-O
                program: -m src.model.tuning
                python: CPython 3.13.2
                root: /Users/brader/Desktop/stock-dashboard
                startedAt: "2025-12-05T20:59:11.749926Z"
                writerId: r2bu9rmhcy6kzyrtd7k9dzbpbkmrqu3x
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "2":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.2
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": darwin-arm64
colsample_bytree:
    value: 0.7008037959698377
learning_rate:
    value: 0.12470961780902594
max_depth:
    value: 4
n_estimators:
    value: 102
reg_alpha:
    value: 7.318265965115034
reg_lambda:
    value: 0.5285156392900402
subsample:
    value: 0.5129907120904452
