_wandb:
    value:
        cli_version: 0.23.1
        e:
            kliqjg62sygtcm7x61ig95oo84hcg4mv:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "7516192768"
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "210250604544"
                email: jan.batman4@gmail.com
                executable: /Users/brader/Desktop/stock-dashboard/venv/bin/python
                git:
                    commit: c814c723c1e3b4c8c4c1869bfab79c4aad71bdbd
                    remote: https://github.com/jjedra4/stock-dashboard.git
                host: Jans-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.0.1-arm64-arm-64bit-Mach-O
                program: -m src.model.tuning
                python: CPython 3.13.2
                root: /Users/brader/Desktop/stock-dashboard
                startedAt: "2025-12-05T20:58:57.099537Z"
                writerId: kliqjg62sygtcm7x61ig95oo84hcg4mv
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "2":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.2
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": darwin-arm64
colsample_bytree:
    value: 0.8895132062797033
learning_rate:
    value: 0.005912325875576884
max_depth:
    value: 2
n_estimators:
    value: 771
reg_alpha:
    value: 4.231167172164753
reg_lambda:
    value: 0.08010115135007978
subsample:
    value: 0.6921235612758009
