_wandb:
    value:
        cli_version: 0.23.1
        e:
            w9onue7ece8zylx2txv1wg7dzu737f3b:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "7516192768"
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "210268446720"
                email: jan.batman4@gmail.com
                executable: /Users/brader/Desktop/stock-dashboard/venv/bin/python
                git:
                    commit: c814c723c1e3b4c8c4c1869bfab79c4aad71bdbd
                    remote: https://github.com/jjedra4/stock-dashboard.git
                host: Jans-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.0.1-arm64-arm-64bit-Mach-O
                program: -m src.model.tuning
                python: CPython 3.13.2
                root: /Users/brader/Desktop/stock-dashboard
                startedAt: "2025-12-05T21:02:36.627187Z"
                writerId: w9onue7ece8zylx2txv1wg7dzu737f3b
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "2":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.2
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": darwin-arm64
colsample_bytree:
    value: 0.8799251257769772
learning_rate:
    value: 0.0776616920851237
max_depth:
    value: 4
n_estimators:
    value: 584
reg_alpha:
    value: 4.478830606960306
reg_lambda:
    value: 9.02695788307181
subsample:
    value: 0.8415268379715494
