_wandb:
    value:
        cli_version: 0.23.1
        e:
            978jvk5mduziklkybehf1lzigvtef2bk:
                email: jan.batman4@gmail.com
                executable: /Users/brader/Desktop/stock-dashboard/venv/bin/python
                git:
                    commit: c814c723c1e3b4c8c4c1869bfab79c4aad71bdbd
                    remote: https://github.com/jjedra4/stock-dashboard.git
                host: Jans-MacBook-Air.local
                os: macOS-15.0.1-arm64-arm-64bit-Mach-O
                program: -m src.model.tuning
                python: CPython 3.13.2
                root: /Users/brader/Desktop/stock-dashboard
                startedAt: "2025-12-05T20:53:20.693939Z"
                writerId: 978jvk5mduziklkybehf1lzigvtef2bk
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "2":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.2
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": darwin-arm64
colsample_bytree:
    value: 0.8924770681838791
learning_rate:
    value: 0.05329205721996568
max_depth:
    value: 3
n_estimators:
    value: 418
reg_alpha:
    value: 1.5006068458491761
reg_lambda:
    value: 0.3676604776542114
subsample:
    value: 0.7000354271030094
