_wandb:
    value:
        cli_version: 0.23.1
        e:
            9w83ic1livm3ty8990k7dq1mo8vz3mjt:
                email: jan.batman4@gmail.com
                executable: /Users/brader/Desktop/stock-dashboard/venv/bin/python
                git:
                    commit: c814c723c1e3b4c8c4c1869bfab79c4aad71bdbd
                    remote: https://github.com/jjedra4/stock-dashboard.git
                host: Jans-MacBook-Air.local
                os: macOS-15.0.1-arm64-arm-64bit-Mach-O
                program: -m src.model.tuning
                python: CPython 3.13.2
                root: /Users/brader/Desktop/stock-dashboard
                startedAt: "2025-12-05T20:59:42.341709Z"
                writerId: 9w83ic1livm3ty8990k7dq1mo8vz3mjt
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "2":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.2
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": darwin-arm64
colsample_bytree:
    value: 0.7628290524962398
learning_rate:
    value: 0.011716251148854785
max_depth:
    value: 3
n_estimators:
    value: 475
reg_alpha:
    value: 4.736416213474364
reg_lambda:
    value: 9.185167138224255
subsample:
    value: 0.7670994658055376
