_wandb:
    value:
        cli_version: 0.23.1
        e:
            ljt8khxdqhrvbgcyml2w6ppdyofcwshl:
                email: jan.batman4@gmail.com
                executable: /Users/brader/Desktop/stock-dashboard/venv/bin/python
                git:
                    commit: c814c723c1e3b4c8c4c1869bfab79c4aad71bdbd
                    remote: https://github.com/jjedra4/stock-dashboard.git
                host: Jans-MacBook-Air.local
                os: macOS-15.0.1-arm64-arm-64bit-Mach-O
                program: -m src.model.tuning
                python: CPython 3.13.2
                root: /Users/brader/Desktop/stock-dashboard
                startedAt: "2025-12-05T20:53:52.487995Z"
                writerId: ljt8khxdqhrvbgcyml2w6ppdyofcwshl
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "2":
                - 1
                - 5
                - 6
                - 8
                - 35
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.2
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": darwin-arm64
colsample_bytree:
    value: 0.7872856226034954
learning_rate:
    value: 0.13665967024885065
max_depth:
    value: 9
n_estimators:
    value: 542
reg_alpha:
    value: 7.448114646458392
reg_lambda:
    value: 7.028181187434582
subsample:
    value: 0.8359741415508426
